const predefinedLanguages = [
  {
    name: "English",
    code: "en",
    culture: "en-US",
    base: true,
    flag: "🇺🇸",
  },
  {
    name: "French",
    code: "fr",
    culture: "fr-FR",
    base: false,
    flag: "🇫🇷",
  },
  {
    name: "Spanish",
    code: "es",
    culture: "es-ES",
    base: false,
    flag: "🇪🇸",
  },
  {
    name: "German",
    code: "de",
    culture: "de-DE",
    base: false,
    flag: "🇩🇪",
  },
  {
    name: "Italian",
    code: "it",
    culture: "it-IT",
    base: false,
    flag: "🇮🇹",
  },
  {
    name: "Portuguese",
    code: "pt",
    culture: "pt-PT",
    base: false,
    flag: "🇵🇹",
  },
  {
    name: "Brazilian Portuguese",
    code: "pt-BR",
    culture: "pt-BR",
    base: false,
    flag: "🇧🇷",
  },
  {
    name: "Russian",
    code: "ru",
    culture: "ru-RU",
    base: false,
    flag: "🇷🇺",
  },
  {
    name: "Japanese",
    code: "ja",
    culture: "ja-JP",
    base: false,
    flag: "🇯🇵",
  },
  {
    name: "Korean",
    code: "ko",
    culture: "ko-KR",
    base: false,
    flag: "🇰🇷",
  },
  {
    name: "Chinese (Simplified)",
    code: "zh-CN",
    culture: "zh-CN",
    base: false,
    flag: "🇨🇳",
  },
  {
    name: "Chinese (Traditional)",
    code: "zh-TW",
    culture: "zh-TW",
    base: false,
    flag: "🇹🇼",
  },
  {
    name: "Arabic",
    code: "ar",
    culture: "ar-SA",
    base: false,
    flag: "🇸🇦",
  },
  {
    name: "Dutch",
    code: "nl",
    culture: "nl-NL",
    base: false,
    flag: "🇳🇱",
  },
  {
    name: "Polish",
    code: "pl",
    culture: "pl-PL",
    base: false,
    flag: "🇵🇱",
  },
  {
    name: "Turkish",
    code: "tr",
    culture: "tr-TR",
    base: false,
    flag: "🇹🇷",
  },
  {
    name: "Swedish",
    code: "sv",
    culture: "sv-SE",
    base: false,
    flag: "🇸🇪",
  },
  {
    name: "Danish",
    code: "da",
    culture: "da-DK",
    base: false,
    flag: "🇩🇰",
  },
  {
    name: "Norwegian",
    code: "nb",
    culture: "nb-NO",
    base: false,
    flag: "🇳🇴",
  },
  {
    name: "Finnish",
    code: "fi",
    culture: "fi-FI",
    base: false,
    flag: "🇫🇮",
  },
  {
    name: "Czech",
    code: "cs",
    culture: "cs-CZ",
    base: false,
    flag: "🇨🇿",
  },
  {
    name: "Greek",
    code: "el",
    culture: "el-GR",
    base: false,
    flag: "🇬🇷",
  },
  {
    name: "Hebrew",
    code: "he",
    culture: "he-IL",
    base: false,
    flag: "🇮🇱",
  },
  {
    name: "Hindi",
    code: "hi",
    culture: "hi-IN",
    base: false,
    flag: "🇮🇳",
  },
  {
    name: "Thai",
    code: "th",
    culture: "th-TH",
    base: false,
    flag: "🇹🇭",
  },
  {
    name: "Vietnamese",
    code: "vi",
    culture: "vi-VN",
    base: false,
    flag: "🇻🇳",
  },
  {
    name: "Indonesian",
    code: "id",
    culture: "id-ID",
    base: false,
    flag: "🇮🇩",
  },
  {
    name: "Ukrainian",
    code: "uk",
    culture: "uk-UA",
    base: false,
    flag: "🇺🇦",
  },
];

export default predefinedLanguages;
